function prompt = buildFieldAnalysisPrompt(fieldStats, structure)
% BUILDFIELDANALYSISPROMPT - Create intelligent prompt for LLM analysis
%
% This function builds a detailed prompt that provides context about
% event fields to an LLM (Claude, GPT-4, etc.) for intelligent classification.
%
% Inputs:
%   fieldStats - Struct with field statistics from discoverEventFields
%   structure - Detected event structure from detectEventStructure
%
% Output:
%   prompt - String containing the formatted prompt for LLM

    % Build the system context
    prompt = sprintf(['You are an expert EEG data analyst specializing in event-related potential (ERP) studies. ', ...
                      'Your task is to analyze event field metadata and classify each field.\n\n']);

    % Add detected format information
    prompt = [prompt sprintf('DETECTED EVENT FORMAT: %s (%.0f%% confidence)\n', ...
                            upper(structure.format), structure.confidence * 100)];
    if ~isempty(structure.eventPattern)
        prompt = [prompt sprintf('Event pattern: "%s"\n', structure.eventPattern)];
    end
    prompt = [prompt sprintf('\n')];

    % Add field analysis instructions
    prompt = [prompt sprintf(['TASK: Classify each field into one of these categories:\n', ...
                             '1. CONDITION - Experimental condition/factor (use for grouping trials)\n', ...
                             '2. TRIAL-SPECIFIC - Trial-level metadata like trial number, response time (exclude from grouping)\n', ...
                             '3. METADATA - EEG system metadata like event type, timestamps (exclude from grouping)\n', ...
                             '4. DEMOGRAPHIC - Participant info like age, sex (exclude from grouping)\n\n'])];

    % Add reasoning guidelines
    prompt = [prompt sprintf(['GUIDELINES:\n', ...
                             '- Low cardinality (<10%%) + meaningful values = likely CONDITION\n', ...
                             '- High cardinality (>50%%) = likely TRIAL-SPECIFIC\n', ...
                             '- Fields with "trial", "time", "latency", "obs" = TRIAL-SPECIFIC\n', ...
                             '- Fields with "age", "sex", "subj", "hand" = DEMOGRAPHIC\n', ...
                             '- Fields like "tracktype", "code", "label" without mffkey prefix = METADATA\n', ...
                             '- Fields with "mffkey_" prefix are usually experimental variables\n', ...
                             '- Look for patterns: G23/SG23 suggests condition codes, y/n suggests binary factor\n\n'])];

    % Add field data
    prompt = [prompt sprintf('FIELD DATA:\n')];
    prompt = [prompt sprintf('%-25s | %12s | %12s | %s\n', 'Field Name', 'Unique Vals', 'Cardinality', 'Sample Values')];
    prompt = [prompt sprintf('%s\n', repmat('-', 1, 100))];

    fieldNames = fieldnames(fieldStats);
    for i = 1:length(fieldNames)
        fieldName = fieldNames{i};
        stats = fieldStats.(fieldName);

        % Format sample values
        sampleVals = stats.uniqueValues(1:min(5, length(stats.uniqueValues)));
        if length(stats.uniqueValues) > 5
            sampleStr = [strjoin(sampleVals, ', '), sprintf(', ... (%d more)', length(stats.uniqueValues) - 5)];
        else
            sampleStr = strjoin(sampleVals, ', ');
        end

        % Limit sample string length
        if length(sampleStr) > 40
            sampleStr = [sampleStr(1:37), '...'];
        end

        prompt = [prompt sprintf('%-25s | %12d | %10.1f%% | %s\n', ...
                                fieldName, stats.numUnique, stats.cardinality * 100, sampleStr)];
    end

    prompt = [prompt sprintf('\n')];

    % Add output format requirements
    prompt = [prompt sprintf(['REQUIRED OUTPUT FORMAT (valid JSON only):\n', ...
                             '{\n', ...
                             '  "grouping_fields": ["field1", "field2"],\n', ...
                             '  "exclude_fields": ["field3", "field4"],\n', ...
                             '  "field_classifications": {\n', ...
                             '    "field1": {"category": "CONDITION", "reasoning": "..."},\n', ...
                             '    "field2": {"category": "CONDITION", "reasoning": "..."},\n', ...
                             '    "field3": {"category": "TRIAL-SPECIFIC", "reasoning": "..."}\n', ...
                             '  },\n', ...
                             '  "recommended_priority_order": ["most_important_field", "second_field"],\n', ...
                             '  "value_mappings": {\n', ...
                             '    "fieldX": {"y": "word", "n": "nonword"}\n', ...
                             '  },\n', ...
                             '  "confidence": 0.95,\n', ...
                             '  "overall_assessment": "This appears to be a lexical decision task..."\n', ...
                             '}\n\n'])];

    prompt = [prompt sprintf(['IMPORTANT:\n', ...
                             '- Only include fields that are clearly CONDITION in grouping_fields\n', ...
                             '- Recommend 2-3 grouping fields maximum (avoid over-fragmentation)\n', ...
                             '- Prioritize mffkey_ experimental fields over system metadata\n', ...
                             '- Provide clear reasoning for each classification\n', ...
                             '- Consider the experimental paradigm when making recommendations\n', ...
                             '- Return ONLY the JSON object, no additional text\n'])];
end
