function prompt = buildFieldAnalysisPrompt(fieldStats, structure, varargin)
% BUILDFIELDANALYSISPROMPT - Create intelligent prompt for LLM analysis
%
% This function builds a detailed prompt that provides context about
% event fields to an LLM (Claude, GPT-4, etc.) for intelligent classification.
%
% Inputs:
%   fieldStats - Struct with field statistics from discoverEventFields
%   structure - Detected event structure from detectEventStructure
%   eventSamples - (Optional) Cell array of sample event structures
%
% Output:
%   prompt - String containing the formatted prompt for LLM

    % Parse optional event samples
    eventSamples = {};
    if nargin >= 3
        eventSamples = varargin{1};
    end

    % Build the system context
    prompt = sprintf(['You are an expert EEG/ERP data analyst with deep knowledge of experimental paradigms. ', ...
                      'Your task is to analyze event metadata, identify the experimental design, and provide ', ...
                      'intelligent recommendations for data analysis.\n\n']);

    % Add detected format information
    prompt = [prompt sprintf('DETECTED EVENT FORMAT: %s (%.0f%% confidence)\n', ...
                            upper(structure.format), structure.confidence * 100)];
    if ~isempty(structure.eventPattern)
        prompt = [prompt sprintf('Event pattern: "%s"\n', structure.eventPattern)];
    end
    prompt = [prompt sprintf('\n')];

    % Add sample events if provided
    if ~isempty(eventSamples)
        prompt = [prompt sprintf('\nSAMPLE EVENTS (actual event structures from the dataset):\n')];
        prompt = [prompt sprintf('These show the real event data structure and values:\n\n')];

        for i = 1:min(25, length(eventSamples))
            evt = eventSamples{i};
            prompt = [prompt sprintf('Event %d:\n', i)];

            % Show event type
            if isfield(evt, 'type')
                prompt = [prompt sprintf('  type: "%s"\n', char(evt.type))];
            end

            % Show all other fields (excluding EEG metadata)
            fnames = fieldnames(evt);
            for f = 1:length(fnames)
                fname = fnames{f};
                % Skip basic EEG fields
                if ismember(fname, {'type', 'latency', 'duration', 'urevent', 'epoch'})
                    continue;
                end
                fval = evt.(fname);
                if ischar(fval) || isstring(fval)
                    prompt = [prompt sprintf('  %s: "%s"\n', fname, char(fval))];
                elseif isnumeric(fval) && isscalar(fval)
                    prompt = [prompt sprintf('  %s: %g\n', fname, fval)];
                end
            end
            prompt = [prompt sprintf('\n')];
        end
    end

    % Add comprehensive task instructions
    prompt = [prompt sprintf(['YOUR TASKS:\n', ...
                             '1. CLASSIFY FIELDS into categories:\n', ...
                             '   - CONDITION: Experimental factors (use for grouping trials)\n', ...
                             '   - TRIAL-SPECIFIC: Trial metadata like number, RT (exclude)\n', ...
                             '   - METADATA: EEG system data like timestamps (exclude)\n', ...
                             '   - DEMOGRAPHIC: Participant info (exclude)\n\n', ...
                             '2. IDENTIFY THE EXPERIMENTAL PARADIGM:\n', ...
                             '   - What type of study is this? (lexical decision, N-back, etc.)\n', ...
                             '   - What are the main experimental manipulations?\n', ...
                             '   - What conditions should be compared?\n\n', ...
                             '3. DETECT PRACTICE TRIALS:\n', ...
                             '   - Identify patterns/values that indicate practice/training trials\n', ...
                             '   - Look for "practice", "training", "Prac", or trial blocks marked differently\n', ...
                             '   - These should be excluded from main analysis\n\n', ...
                             '4. RECOMMEND WHICH CONDITIONS TO ANALYZE:\n', ...
                             '   - Which event types/conditions are the main experimental trials?\n', ...
                             '   - Which should be excluded? (practice, calibration, breaks, etc.)\n', ...
                             '   - Suggest meaningful condition groupings for ERP analysis\n\n'])];

    % Add reasoning guidelines
    prompt = [prompt sprintf(['GUIDELINES:\n', ...
                             '- Low cardinality (<10%%) + meaningful values = likely CONDITION\n', ...
                             '- High cardinality (>50%%) = likely TRIAL-SPECIFIC\n', ...
                             '- Fields with "trial", "time", "latency", "obs" = TRIAL-SPECIFIC\n', ...
                             '- Fields with "age", "sex", "subj", "hand" = DEMOGRAPHIC\n', ...
                             '- Fields like "tracktype", "code", "label" without mffkey prefix = METADATA\n', ...
                             '- Fields with "mffkey_" prefix are usually experimental variables\n', ...
                             '- Look for patterns: G23/SG23 suggests condition codes, y/n suggests binary factor\n\n'])];

    % Add field data
    prompt = [prompt sprintf('FIELD DATA:\n')];
    prompt = [prompt sprintf('%-25s | %12s | %12s | %s\n', 'Field Name', 'Unique Vals', 'Cardinality', 'Sample Values')];
    prompt = [prompt sprintf('%s\n', repmat('-', 1, 100))];

    fieldNames = fieldnames(fieldStats);
    for i = 1:length(fieldNames)
        fieldName = fieldNames{i};
        stats = fieldStats.(fieldName);

        % Format sample values (show up to 15 values)
        sampleVals = stats.uniqueValues(1:min(15, length(stats.uniqueValues)));
        if length(stats.uniqueValues) > 15
            sampleStr = [strjoin(sampleVals, ', '), sprintf(', ... (%d more)', length(stats.uniqueValues) - 15)];
        else
            sampleStr = strjoin(sampleVals, ', ');
        end

        % Limit sample string length (increased to accommodate more values)
        if length(sampleStr) > 80
            sampleStr = [sampleStr(1:77), '...'];
        end

        prompt = [prompt sprintf('%-25s | %12d | %10.1f%% | %s\n', ...
                                fieldName, stats.numUnique, stats.cardinality * 100, sampleStr)];
    end

    prompt = [prompt sprintf('\n')];

    % Add output format requirements
    prompt = [prompt sprintf(['REQUIRED OUTPUT FORMAT (valid JSON only):\n', ...
                             '{\n', ...
                             '  "experimental_paradigm": {\n', ...
                             '    "type": "lexical_decision",\n', ...
                             '    "description": "Participants distinguish words from nonwords",\n', ...
                             '    "key_manipulations": ["lexicality", "word_frequency"]\n', ...
                             '  },\n', ...
                             '  "practice_trial_patterns": [\n', ...
                             '    {"pattern": "Practice", "field": "condition", "reasoning": "..."},\n', ...
                             '    {"pattern": "Prac", "field": "event_type", "reasoning": "..."}\n', ...
                             '  ],\n', ...
                             '  "condition_recommendations": {\n', ...
                             '    "include": ["word", "nonword", "high_freq", "low_freq"],\n', ...
                             '    "exclude": ["practice", "calibration", "break"],\n', ...
                             '    "primary_comparisons": [\n', ...
                             '      {"condition_a": "word", "condition_b": "nonword", "erp_component": "N400"},\n', ...
                             '      {"condition_a": "high_freq", "condition_b": "low_freq", "erp_component": "N400"}\n', ...
                             '    ]\n', ...
                             '  },\n', ...
                             '  "grouping_fields": ["field1", "field2"],\n', ...
                             '  "exclude_fields": ["field3", "field4"],\n', ...
                             '  "field_classifications": {\n', ...
                             '    "field1": {"category": "CONDITION", "reasoning": "..."},\n', ...
                             '    "field2": {"category": "CONDITION", "reasoning": "..."},\n', ...
                             '    "field3": {"category": "TRIAL-SPECIFIC", "reasoning": "..."}\n', ...
                             '  },\n', ...
                             '  "recommended_priority_order": ["most_important_field", "second_field"],\n', ...
                             '  "value_mappings": {\n', ...
                             '    "fieldX": {"y": "word", "n": "nonword"}\n', ...
                             '  },\n', ...
                             '  "confidence": 0.95,\n', ...
                             '  "overall_assessment": "This is a lexical decision task with word/nonword manipulation. Practice trials detected in block 1. Recommend comparing N400 amplitudes between word and nonword conditions."\n', ...
                             '}\n\n'])];

    prompt = [prompt sprintf(['IMPORTANT:\n', ...
                             '- Analyze the SAMPLE EVENTS carefully to understand the data structure\n', ...
                             '- Be specific about which event types/values indicate practice trials\n', ...
                             '- CRITICAL: Practice patterns must NOT be empty strings - only include if you find clear evidence\n', ...
                             '- Only include practice patterns if you see keywords like "Prac", "Practice", "training", etc.\n', ...
                             '- Recommend which specific condition values to INCLUDE in analysis (be explicit!)\n', ...
                             '- Recommend which specific condition values to EXCLUDE (practice, breaks, calibration)\n', ...
                             '- The include/exclude lists will be used to filter actual data - be precise!\n', ...
                             '- Suggest relevant ERP components for each comparison (N400, P600, N250, P300, etc.)\n', ...
                             '- Only include fields that are clearly CONDITION in grouping_fields\n', ...
                             '- Recommend 2-3 grouping fields maximum (avoid over-fragmentation)\n', ...
                             '- Prioritize mffkey_ experimental fields over system metadata\n', ...
                             '- Provide clear reasoning for all recommendations\n', ...
                             '- Consider the experimental paradigm when making recommendations\n', ...
                             '- Return ONLY the JSON object, no additional text\n', ...
                             '- Do NOT include empty strings ("") in any arrays\n'])];
end
